name: flutter_games
description: Flutter app for purchasing and renting games.

version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  responsive_framework: ^0.0.7
  percent_indicator: "^2.1.1"
  rxdart: ^0.22.0
  get_it: ^1.0.3+2
  rflutter_alert: ^1.0.3
  audioplayers: ^0.13.0
  sliding_up_panel: ^0.3.4
  device_info: ^2.0.2
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/Game-Controller-Logo.png"
  image_path_ios: "assets/Game-Controller-Logo-iOS.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/Game-Controller-Logo-Adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - images/
    - images/solitaire/

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.13.8 <2.0.0"